### ISSUE TITLE
build/run issue

### ISSUE THREAD

**Issue by sraihan** [CPqD/oftest12#2]
Hi,
I have installed it in cygwin. Got no errors. But running throws errors as follows,

sraihan@GAW-SRAIHAN-01 ~/oftest12/tests
$ ./oft --list
Traceback (most recent call last):
  File "./oft", line 128, in <module>
    import testutils
  File "/home/sraihan/oftest12/tests/testutils.py", line 13, in <module>
    import oftest.parse as parse
  File "build/bdist.cygwin-1.7.16-i686/egg/oftest/parse.py", line 25, in <module>
NameError: name 'sys' is not defined

My build log is as follows.

sraihan@GAW-SRAIHAN-01 ~/oftest12/tools/munger
$ make install
(cd ../../src/python/ && python setup.py install)
running install
running bdist_egg
running egg_info
writing requirements to oftest.egg-info/requires.txt
writing oftest.egg-info/PKG-INFO
writing top-level names to oftest.egg-info/top_level.txt
writing dependency_links to oftest.egg-info/dependency_links.txt
reading manifest file 'oftest.egg-info/SOURCES.txt'
writing manifest file 'oftest.egg-info/SOURCES.txt'
installing library code to build/bdist.cygwin-1.7.16-i686/egg
running install_lib
running build_py
creating build/bdist.cygwin-1.7.16-i686/egg
creating build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/action.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/action_list.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/base_list.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/bucket.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/bucket_list.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/class_maps.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/controller.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/cstruct.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/dataplane.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/error.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/instruction.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/instruction_list.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/match.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/match_list.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/message.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/message_unittests.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/netutils.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/oft_assert.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/ofutils.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/packet.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/parse.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/unittests.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
copying build/lib/oftest/**init**.py -> build/bdist.cygwin-1.7.16-i686/egg/oftest
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/action.py to action.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/action_list.py to action_list.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/base_list.py to base_list.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/bucket.py to bucket.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/bucket_list.py to bucket_list.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/class_maps.py to class_maps.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/controller.py to controller.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/cstruct.py to cstruct.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/dataplane.py to dataplane.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/error.py to error.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/instruction.py to instruction.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/instruction_list.py to instruction_list.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/match.py to match.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/match_list.py to match_list.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/message.py to message.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/message_unittests.py to message_unittests.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/netutils.py to netutils.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/oft_assert.py to oft_assert.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/ofutils.py to ofutils.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/packet.py to packet.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/parse.py to parse.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/unittests.py to unittests.pyc
byte-compiling build/bdist.cygwin-1.7.16-i686/egg/oftest/**init**.py to **init**.pyc
creating build/bdist.cygwin-1.7.16-i686/egg/EGG-INFO
copying oftest.egg-info/PKG-INFO -> build/bdist.cygwin-1.7.16-i686/egg/EGG-INFO
copying oftest.egg-info/SOURCES.txt -> build/bdist.cygwin-1.7.16-i686/egg/EGG-INFO
copying oftest.egg-info/dependency_links.txt -> build/bdist.cygwin-1.7.16-i686/egg/EGG-INFO
copying oftest.egg-info/requires.txt -> build/bdist.cygwin-1.7.16-i686/egg/EGG-INFO
copying oftest.egg-info/top_level.txt -> build/bdist.cygwin-1.7.16-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/oftest-0.0.1-py2.6.egg' and adding 'build/bdist.cygwin-1.7.16-i686/egg' to it
removing 'build/bdist.cygwin-1.7.16-i686/egg' (and everything under it)
Processing oftest-0.0.1-py2.6.egg
Removing /usr/lib/python2.6/site-packages/oftest-0.0.1-py2.6.egg
Copying oftest-0.0.1-py2.6.egg to /usr/lib/python2.6/site-packages
oftest 0.0.1 is already the active version in easy-install.pth

Installed /usr/lib/python2.6/site-packages/oftest-0.0.1-py2.6.egg
Processing dependencies for oftest==0.0.1
Searching for pylint==0.25.2
Best match: pylint 0.25.2
Processing pylint-0.25.2-py2.6.egg
pylint 0.25.2 is already the active version in easy-install.pth
Installing epylint script to /usr/bin
Installing pylint script to /usr/bin
Installing pylint-gui script to /usr/bin
Installing pyreverse script to /usr/bin
Installing symilar script to /usr/bin

Using /usr/lib/python2.6/site-packages/pylint-0.25.2-py2.6.egg
Searching for doxypy==0.4.2
Best match: doxypy 0.4.2
Processing doxypy-0.4.2-py2.6.egg
doxypy 0.4.2 is already the active version in easy-install.pth
Installing doxypy.py script to /usr/bin

Using /usr/lib/python2.6/site-packages/doxypy-0.4.2-py2.6.egg
Searching for setuptools==0.6c11
Best match: setuptools 0.6c11
Processing setuptools-0.6c11-py2.6.egg
setuptools 0.6c11 is already the active version in easy-install.pth
Installing easy_install script to /usr/bin
Installing easy_install-2.6 script to /usr/bin

Using /usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg
Searching for logilab-astng==0.24.0
Best match: logilab-astng 0.24.0
Processing logilab_astng-0.24.0-py2.6.egg
logilab-astng 0.24.0 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/logilab_astng-0.24.0-py2.6.egg
Searching for logilab-common==0.58.1
Best match: logilab-common 0.58.1
Processing logilab_common-0.58.1-py2.6.egg
logilab-common 0.58.1 is already the active version in easy-install.pth
Installing pytest script to /usr/bin

Using /usr/lib/python2.6/site-packages/logilab_common-0.58.1-py2.6.egg
Searching for unittest2==0.5.1
Best match: unittest2 0.5.1
Processing unittest2-0.5.1-py2.6.egg
unittest2 0.5.1 is already the active version in easy-install.pth
Installing unit2 script to /usr/bin
Installing unit2.py script to /usr/bin
Installing unit2-2.6 script to /usr/bin
Installing unit2 script to /usr/bin

Using /usr/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg
Finished processing dependencies for oftest==0.0.1

**Comment by rrdenicol** [comment]
Hello sraihan,

I have uploaded a small fix to this issue. Just pulling the changes and re-making the project should solve it.

But you might get another error on running oftest, because it seems to me that you may not have scapy installed properly.

**Comment by sraihan** [comment]
Thanks for the fix. Yes I am having issues with scapy working with oftest12. 
oftest (1.0) seems print list of test on cygwin but oftest12 does not.
Any suggestion thanks?
